# List of plugins
set -g @plugin "fabioluciano/tmux-powerkit"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-pain-control"
set -g @plugin "tmux-plugins/tpm"

# Basic configuration
set -g base-index 1
set -g default-shell "/usr/bin/fish"
set -g default-terminal "tmux-256color"
set -g history-limit 100000
set -g renumber-windows on
set -ga terminal-overrides ",xterm-256color:Tc"

# Window configuration
set -gw mode-keys "vi"
set -gw pane-base-index 1

# Powerkit configuration
set -g @powerkit_plugins ""
set -g @powerkit_separator_style "rounded"
set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "mocha"

# Key binding configuration - window mode
bind-key -n C-t switch-client -T window_mode
bind-key -T window_mode n new-window
bind-key -T window_mode x kill-window
bind-key -T window_mode r command-prompt "rename-window '%%'"
bind-key -T window_mode Left previous-window
bind-key -T window_mode Right next-window
bind-key -T window_mode 1 select-window -t 1
bind-key -T window_mode 2 select-window -t 2
bind-key -T window_mode 3 select-window -t 3
bind-key -T window_mode 4 select-window -t 4
bind-key -T window_mode 5 select-window -t 5
bind-key -T window_mode 6 select-window -t 6
bind-key -T window_mode 7 select-window -t 7
bind-key -T window_mode 8 select-window -t 8
bind-key -T window_mode 9 select-window -t 9

# Key binding configuration - pane mode
bind-key -n C-p switch-client -T pane_mode
bind-key -T pane_mode h split-window -h -c "#{pane_current_path}"
bind-key -T pane_mode v split-window -v -c "#{pane_current_path}"
bind-key -T pane_mode x kill-pane
bind-key -T pane_mode f resize-pane -Z
bind-key -T pane_mode w swap-pane -D
bind-key -T pane_mode Left select-pane -L
bind-key -T pane_mode Down select-pane -D
bind-key -T pane_mode Up select-pane -U
bind-key -T pane_mode Right select-pane -R

# Key binding configuration - resize mode
bind-key -n C-n switch-client -T resize_mode
bind-key -T resize_mode Left resize-pane -L 5
bind-key -T resize_mode Down resize-pane -D 5
bind-key -T resize_mode Up resize-pane -U 5
bind-key -T resize_mode Right resize-pane -R 5

# Key binding configuration - scroll mode
bind-key -n C-s copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Key binding configuration - session mode
bind-key -n C-o switch-client -T session_mode
bind-key -T session_mode d detach-client
bind-key -T session_mode w choose-tree -Zs
bind-key -n C-q kill-pane

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
