#!/bin/bash

git submodule update --init
git submodule update --remote

cp    -Rf .config                 ~/
mkdir -p  ~/.vim
ln    -sf ~/.config/nvim/init.vim ~/.vimrc
ln    -sf ~/.config/nvim/autoload ~/.vim/autoload
ln    -sf ~/.config/nvim/bundle   ~/.vim/bundle

cp    -Rf .tmux                    ~/
cp    -f  .tmux.conf               ~/
cp    -f  .promptline.conf         ~/
cp    -f  .tmuxline.conf           ~/

cat       .bashrc >>               ~/.bashrc
