#!/bin/bash

git submodule update --init
git submodule update --remote

cp    -R  .config                 ~/
mkdir -p  ~/.vim
ln    -sf ~/.config/nvim/init.vim ~/.vimrc
ln    -sf ~/.config/nvim/autoload ~/.vim/autoload
ln    -sf ~/.config/nvim/bundle   ~/.vim/bundle

cp    -R  .tmux                    ~/
cp        .tmux.conf               ~/
cp        .promptline.conf         ~/
cp        .tmuxline.conf           ~/

cat       .bashrc >>               ~/.bashrc
