# git-mktree
# Autogenerated from man page /usr/share/man/man1/git-mktree.1.gz
complete -c git -n '__fish_git_using_command mktree' -s z --description 'Read the NUL-terminated ls-tree -z output instead.'
complete -c git -n '__fish_git_using_command mktree' -l missing --description 'Allow missing objects.'
complete -c git -n '__fish_git_using_command mktree' -l batch --description 'Allow building of more than one tree object before exiting.'

