# git-mv
# Autogenerated from man page /usr/share/man/man1/git-mv.1.gz
complete -c git -n '__fish_git_using_command mv' -s f -l force --description 'Force renaming or moving of a file even if the target exists.'
complete -c git -n '__fish_git_using_command mv' -s k --description 'Skip move or rename actions which would lead to an error condition.'
complete -c git -n '__fish_git_using_command mv' -s n -l dry-run --description 'Do nothing; only show what would happen.'
complete -c git -n '__fish_git_using_command mv' -s v -l verbose --description 'Report the names of files as they are moved.'

