# git-mailsplit
# Autogenerated from man page /usr/share/man/man1/git-mailsplit.1.gz
complete -c git -n '__fish_git_using_command mailsplit' -o 'o<directory>' --description 'Directory in which to place the individual messages.'
complete -c git -n '__fish_git_using_command mailsplit' -s b --description 'If any file doesn\\(cqt begin with a From line, assume it is a single mail mes…'
complete -c git -n '__fish_git_using_command mailsplit' -o 'd<prec>' --description 'Instead of the default 4 digits with leading zeros, different precision can b…'
complete -c git -n '__fish_git_using_command mailsplit' -o 'f<nn>' --description 'Skip the first <nn> numbers, for example if -f3 is specified, start the numbe…'
complete -c git -n '__fish_git_using_command mailsplit' -l keep-cr --description 'Do not remove r from lines ending with rn.'
complete -c git -n '__fish_git_using_command mailsplit' -l mboxrd --description 'Input is of the "mboxrd" format and "^>+From " line escaping is reversed.'

