# git-cat-file
# Autogenerated from man page /usr/share/man/man1/git-cat-file.1.gz
complete -c git -n '__fish_git_using_command cat-file' -s t --description 'Instead of the content, show the object type identified by <object>.'
complete -c git -n '__fish_git_using_command cat-file' -s s --description 'Instead of the content, show the object size identified by <object>.'
complete -c git -n '__fish_git_using_command cat-file' -s e --description 'Exit with zero status if <object> exists and is a valid object.'
complete -c git -n '__fish_git_using_command cat-file' -s p --description 'Pretty-print the contents of <object> based on its type.'
complete -c git -n '__fish_git_using_command cat-file' -l textconv --description 'Show the content as transformed by a textconv filter.'
complete -c git -n '__fish_git_using_command cat-file' -l filters --description 'Show the content as converted by the filters configured in the current workin…'
complete -c git -n '__fish_git_using_command cat-file' -l path --description 'For use with --textconv or --filters, to allow specifying an object name and …'
complete -c git -n '__fish_git_using_command cat-file' -l batch -l batch --description 'Print object information and contents for each object provided on stdin.'
complete -c git -n '__fish_git_using_command cat-file' -l batch-check -l batch-check --description 'Print object information for each object provided on stdin.'
complete -c git -n '__fish_git_using_command cat-file' -l batch-all-objects --description 'Instead of reading a list of objects on stdin, perform the requested batch op…'
complete -c git -n '__fish_git_using_command cat-file' -l buffer --description 'Normally batch output is flushed after each object is output, so that a proce…'
complete -c git -n '__fish_git_using_command cat-file' -l unordered --description 'When --batch-all-objects is in use, visit objects in an order which may be mo…'
complete -c git -n '__fish_git_using_command cat-file' -l allow-unknown-type --description 'Allow -s or -t to query broken/corrupt objects of unknown type.'
complete -c git -n '__fish_git_using_command cat-file' -l follow-symlinks --description 'With --batch or --batch-check, follow symlinks inside the repository when req…'

