# git-verify-pack
# Autogenerated from man page /usr/share/man/man1/git-verify-pack.1.gz
complete -c git -n '__fish_git_using_command verify-pack' -s v -l verbose --description 'After verifying the pack, show list of objects contained in the pack and a hi…'
complete -c git -n '__fish_git_using_command verify-pack' -s s -l stat-only --description 'Do not verify the pack contents; only show the histogram of delta chain lengt…'

