# git-credential-store
# Autogenerated from man page /usr/share/man/man1/git-credential-store.1.gz
complete -c git -n '__fish_git_using_command credential-store' -l file --description 'Use <path> to lookup and store credentials.'

