# git-revert
# Autogenerated from man page /usr/share/man/man1/git-revert.1.gz
complete -c git -n '__fish_git_using_command revert' -s e -l edit --description 'With this option, git revert will let you edit the commit message prior to co…'
complete -c git -n '__fish_git_using_command revert' -s m -l mainline --description 'Usually you cannot revert a merge because you do not know which side of the m…'
complete -c git -n '__fish_git_using_command revert' -l no-edit --description 'With this option, git revert will not start the commit message editor.'
complete -c git -n '__fish_git_using_command revert' -s n -l no-commit --description 'Usually the command automatically creates some commits with commit log messag…'
complete -c git -n '__fish_git_using_command revert' -s S -l gpg-sign --description 'GPG-sign commits.'
complete -c git -n '__fish_git_using_command revert' -s s -l signoff --description 'Add Signed-off-by line at the end of the commit message.'
complete -c git -n '__fish_git_using_command revert' -l strategy --description 'Use the given merge strategy.  Should only be used once.'
complete -c git -n '__fish_git_using_command revert' -o 'X<option>' -l strategy-option --description 'Pass the merge strategy-specific option through to the merge strategy.'
complete -c git -n '__fish_git_using_command revert' -l no-walk --description 'option.'
complete -c git -n '__fish_git_using_command revert' -l continue --description '.'
complete -c git -n '__fish_git_using_command revert' -l quit --description '.'
complete -c git -n '__fish_git_using_command revert' -l abort --description '.'

