# git-prune-packed
# Autogenerated from man page /usr/share/man/man1/git-prune-packed.1.gz
complete -c git -n '__fish_git_using_command prune-packed' -s n -l dry-run --description 'Don\\(cqt actually remove any objects, only show those that would have been re…'
complete -c git -n '__fish_git_using_command prune-packed' -s q -l quiet --description 'Squelch the progress indicator.'

