# git-pack-redundant
# Autogenerated from man page /usr/share/man/man1/git-pack-redundant.1.gz
complete -c git -n '__fish_git_using_command pack-redundant' -l all --description 'Processes all packs.  Any filenames on the command line are ignored.'
complete -c git -n '__fish_git_using_command pack-redundant' -l alt-odb --description 'Don\\(cqt require objects present in packs from alternate object directories t…'
complete -c git -n '__fish_git_using_command pack-redundant' -l verbose --description 'Outputs some statistics to stderr.  Has a small performance penalty.'

