# git-check-attr
# Autogenerated from man page /usr/share/man/man1/git-check-attr.1.gz
complete -c git -n '__fish_git_using_command check-attr' -s a -l all --description 'List all attributes that are associated with the specified paths.'
complete -c git -n '__fish_git_using_command check-attr' -l cached --description 'Consider . gitattributes in the index only, ignoring the working tree.'
complete -c git -n '__fish_git_using_command check-attr' -l stdin --description 'Read pathnames from the standard input, one per line, instead of from the com…'
complete -c git -n '__fish_git_using_command check-attr' -s z --description 'The output format is modified to be machine-parseable.'

