# git-prune
# Autogenerated from man page /usr/share/man/man1/git-prune.1.gz
complete -c git -n '__fish_git_using_command prune' -s n -l dry-run --description 'Do not remove anything; just report what it would remove.'
complete -c git -n '__fish_git_using_command prune' -s v -l verbose --description 'Report all removed objects.'
complete -c git -n '__fish_git_using_command prune' -l progress --description 'Show progress.'
complete -c git -n '__fish_git_using_command prune' -l expire --description 'Only expire loose objects older than <time>.'

