# git-fsck
# Autogenerated from man page /usr/share/man/man1/git-fsck.1.gz
complete -c git -n '__fish_git_using_command fsck' -l unreachable --description 'Print out objects that exist but that aren\\(cqt reachable from any of the ref…'
complete -c git -n '__fish_git_using_command fsck' -l dangling --description 'Print objects that exist but that are never directly used (default).'
complete -c git -n '__fish_git_using_command fsck' -l root --description 'Report root nodes.'
complete -c git -n '__fish_git_using_command fsck' -l tags --description 'Report tags.'
complete -c git -n '__fish_git_using_command fsck' -l cache --description 'Consider any object recorded in the index also as a head node for an unreacha…'
complete -c git -n '__fish_git_using_command fsck' -l no-reflogs --description 'Do not consider commits that are referenced only by an entry in a reflog to b…'
complete -c git -n '__fish_git_using_command fsck' -l full --description 'Check not just objects in GIT_OBJECT_DIRECTORY ($GIT_DIR/objects), but also t…'
complete -c git -n '__fish_git_using_command fsck' -l connectivity-only --description 'Check only the connectivity of tags, commits and tree objects.'
complete -c git -n '__fish_git_using_command fsck' -l strict --description 'Enable more strict checking, namely to catch a file mode recorded with g+w bi…'
complete -c git -n '__fish_git_using_command fsck' -l verbose --description 'Be chatty.'
complete -c git -n '__fish_git_using_command fsck' -l lost-found --description 'Write dangling objects into . git/lost-found/commit/ or .'
complete -c git -n '__fish_git_using_command fsck' -l name-objects --description 'When displaying names of reachable objects, in addition to the SHA-1 also dis…'
complete -c git -n '__fish_git_using_command fsck' -l progress --description 'Progress status is reported on the standard error stream by default when it i…'
complete -c git -n '__fish_git_using_command fsck' -l no-dangling --description 'can be used to omit this information from the output.'

