# git-web--browse
# Autogenerated from man page /usr/share/man/man1/git-web--browse.1.gz
complete -c git -n '__fish_git_using_command web--browse' -s b -l browser --description 'Use the specified browser.  It must be in the list of supported browsers.'
complete -c git -n '__fish_git_using_command web--browse' -s t -l tool --description 'Same as above.'
complete -c git -n '__fish_git_using_command web--browse' -s c -l config --description 'CONF. VAR is looked up in the Git config files.'

