# git-help
# Autogenerated from man page /usr/share/man/man1/git-help.1.gz
complete -c git -n '__fish_git_using_command help' -s a -l all --description 'Prints all the available commands on the standard output.'
complete -c git -n '__fish_git_using_command help' -l verbose --description 'When used with --all print description for all recognized commands.'
complete -c git -n '__fish_git_using_command help' -s c -l config --description 'List all available configuration variables.'
complete -c git -n '__fish_git_using_command help' -s g -l guides --description 'Prints a list of useful guides on the standard output.'
complete -c git -n '__fish_git_using_command help' -s i -l info --description 'Display manual page for the command in the info format.'
complete -c git -n '__fish_git_using_command help' -s m -l man --description 'Display manual page for the command in the man format.'
complete -c git -n '__fish_git_using_command help' -s w -l web --description 'Display manual page for the command in the web (HTML) format.'

