# git-commit-tree
# Autogenerated from man page /usr/share/man/man1/git-commit-tree.1.gz
complete -c git -n '__fish_git_using_command commit-tree' -s p --description 'Each -p indicates the id of a parent commit object.'
complete -c git -n '__fish_git_using_command commit-tree' -s m --description 'A paragraph in the commit log message.'
complete -c git -n '__fish_git_using_command commit-tree' -s F --description 'Read the commit log message from the given file.'
complete -c git -n '__fish_git_using_command commit-tree' -s S -l gpg-sign --description 'GPG-sign commits.'
complete -c git -n '__fish_git_using_command commit-tree' -l no-gpg-sign --description 'Do not GPG-sign commit, to countermand a --gpg-sign option given earlier on t…'

