# git-upload-pack
# Autogenerated from man page /usr/share/man/man1/git-upload-pack.1.gz
complete -c git -n '__fish_git_using_command upload-pack' -l strict --description 'Do not try <directory>/. git/ if <directory> is no Git directory.'
complete -c git -n '__fish_git_using_command upload-pack' -l timeout --description 'Interrupt transfer after <n> seconds of inactivity.'
complete -c git -n '__fish_git_using_command upload-pack' -l stateless-rpc --description 'Perform only a single read-write cycle with stdin and stdout.'
complete -c git -n '__fish_git_using_command upload-pack' -l advertise-refs --description 'Only the initial ref advertisement is output, and the program exits immediate…'

