# git-request-pull
# Autogenerated from man page /usr/share/man/man1/git-request-pull.1.gz
complete -c git -n '__fish_git_using_command request-pull' -s p --description 'Include patch text in the output.'

