# git-stripspace
# Autogenerated from man page /usr/share/man/man1/git-stripspace.1.gz
complete -c git -n '__fish_git_using_command stripspace' -s s -l strip-comments --description 'Skip and remove all lines starting with comment character (default #).'
complete -c git -n '__fish_git_using_command stripspace' -s c -l comment-lines --description 'Prepend comment character and blank to each line.'

