# git-quiltimport
# Autogenerated from man page /usr/share/man/man1/git-quiltimport.1.gz
complete -c git -n '__fish_git_using_command quiltimport' -s n -l dry-run --description 'Walk through the patches in the series and warn if we cannot find all of the …'
complete -c git -n '__fish_git_using_command quiltimport' -l author --description 'The author name and email address to use when no author information can be fo…'
complete -c git -n '__fish_git_using_command quiltimport' -l patches --description 'The directory to find the quilt patches.'
complete -c git -n '__fish_git_using_command quiltimport' -l series --description 'The quilt series file.'
complete -c git -n '__fish_git_using_command quiltimport' -l keep-non-patch --description 'Pass -b flag to git mailinfo (see git-mailinfo(1)).'
complete -c git -n '__fish_git_using_command quiltimport' -s b --description 'flag to git mailinfo (see git-mailinfo(1)).'

