# git-init
# Autogenerated from man page /usr/share/man/man1/git-init.1.gz
complete -c git -n '__fish_git_using_command init' -s q -l quiet --description 'Only print error and warning messages; all other output will be suppressed.'
complete -c git -n '__fish_git_using_command init' -l bare --description 'Create a bare repository.'
complete -c git -n '__fish_git_using_command init' -l template --description 'Specify the directory from which templates will be used.'
complete -c git -n '__fish_git_using_command init' -l separate-git-dir --description 'Instead of initializing the repository as a directory to either $GIT_DIR or .'
complete -c git -n '__fish_git_using_command init' -l shared --description '.'

