# git-count-objects
# Autogenerated from man page /usr/share/man/man1/git-count-objects.1.gz
complete -c git -n '__fish_git_using_command count-objects' -s v -l verbose --description 'Report in more detail: . sp count: the number of loose objects .'
complete -c git -n '__fish_git_using_command count-objects' -s H -l human-readable --description 'Print sizes in human readable format.'

