# git-reflog
# Autogenerated from man page /usr/share/man/man1/git-reflog.1.gz
complete -c git -n '__fish_git_using_command reflog' -l all --description 'Process the reflogs of all references.'
complete -c git -n '__fish_git_using_command reflog' -l single-worktree --description 'By default when --all is specified, reflogs from all working trees are proces…'
complete -c git -n '__fish_git_using_command reflog' -l expire --description 'Prune entries older than the specified time.'
complete -c git -n '__fish_git_using_command reflog' -l expire-unreachable --description 'Prune entries older than <time> that are not reachable from the current tip o…'
complete -c git -n '__fish_git_using_command reflog' -l updateref --description 'Update the reference to the value of the top reflog entry (i. e.'
complete -c git -n '__fish_git_using_command reflog' -l rewrite --description 'If a reflog entry\\(cqs predecessor is pruned, adjust its "old" SHA-1 to be eq…'
complete -c git -n '__fish_git_using_command reflog' -l stale-fix --description 'Prune any reflog entries that point to "broken commits".'
complete -c git -n '__fish_git_using_command reflog' -s n -l dry-run --description 'Do not actually prune any entries; just show what would have been pruned.'
complete -c git -n '__fish_git_using_command reflog' -l verbose --description 'Print extra information on screen.'

