# git-verify-commit
# Autogenerated from man page /usr/share/man/man1/git-verify-commit.1.gz
complete -c git -n '__fish_git_using_command verify-commit' -l raw --description 'Print the raw gpg status output to standard error instead of the normal human…'
complete -c git -n '__fish_git_using_command verify-commit' -s v -l verbose --description 'Print the contents of the commit object before validating it.'

