# git-verify-tag
# Autogenerated from man page /usr/share/man/man1/git-verify-tag.1.gz
complete -c git -n '__fish_git_using_command verify-tag' -l raw --description 'Print the raw gpg status output to standard error instead of the normal human…'
complete -c git -n '__fish_git_using_command verify-tag' -s v -l verbose --description 'Print the contents of the tag object before validating it.'

