# git-check-mailmap
# Autogenerated from man page /usr/share/man/man1/git-check-mailmap.1.gz
complete -c git -n '__fish_git_using_command check-mailmap' -l stdin --description 'Read contacts, one per line, from the standard input after exhausting contact…'

