# List of plugins
set -g @plugin "dracula/tmux"
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"

# Options to make tmux more pleasant
set -g default-shell "/usr/bin/fish"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g status-position top

# Configure the dracula plugin
set -g @dracula-show-left-icon "#h"
set -g @dracula-show-left-sep ""
set -g @dracula-show-right-sep ""
set -g @dracula-show-powerline true
set -g @dracula-show-edge-icons false
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-refresh-rate 10
set -g @dracula-show-empty-plugins false
set -g @dracula-day-month true
set -g @dracula-military-time true

# Initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
